name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: mic check
        run: echo ${{ secrets.SELLER_ID }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: mic check again
        run: ls ${{ github.workspace }}

      - name: Run a one-line script
        run: echo $(date)

      - name: Run hello_world
        uses: adityak1429/autoPublisher_cli@v1
        with:
          seller-id: ${{secrets.SELLER_ID}}
          tenant-id: ${{secrets.AZURE_AD_TENANT_ID}}
          client-id: ${{secrets.AZURE_AD_APPLICATION_CLIENT_ID}}
          client-secret: ${{secrets.AZURE_AD_APPLICATION_SECRET}}
          
