name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: mic check
        run: echo ${{ secrets.SELLER_ID }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: mic check again
        run: ls ${{ github.workspace }}

      - name: Run a one-line script
        run: echo $(date)
