name: MSStore CLI
trigger:
- main
pool:
  vmImage: 'windows-latest'
steps:
- checkout: self
- task: UseMSStoreCLI@0
- script: msstore reconfigure --tenantId ${{secrets.AZURE_AD_TENANT_ID}} --sellerId ${{SELLER_ID}} --clientId ${{AZURE_AD_APPLICATION_CLIENT_ID}} --clientSecret ${{AZURE_AD_APPLICATION_SECRET}}
- script: msstore apps list
