# .github/workflows/upload-artifact.yml
name: Generate PDP Preview & Upload

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Generate HTML file
        run: |
          mkdir -p output
          echo "<html><body><h1>Microsoft Store PDP Preview</h1></body></html>" > output/preview.html

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdp-preview
          path: output/preview.html
