name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls ${{ github.workspace }}

      - name: Trying to publish
        uses: trympet/microsoft-store-flight-action@v1.0.0
        with:
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
          app-id: ${{ secrets.STORE_APP_ID }}
          flight-id: ${{ secrets.STORE_FLIGHT_ID }}
          package-path: "${{ github.workspace }}/ReleaseSigned/MyApp.msixupload"
          delete-pending: true
          delete-packages: true
          packages-keep: 1
