name: MSStore CLI

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run with MSStore CLI'
        required: true
        default: 'publish'
      interactive:
        description: 'Command to run with MSStore CLI'
        required: true
        default: 'publish'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSStore CLI
      uses: microsoft/setup-msstore-cli@v1.1

    - name: Run AutoPublisher
      uses: adityak1429/autopublisher@main
      with:
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
        seller-id: ${{ secrets.SELLER_ID }}
        command: ${{ github.event.inputs.command }}
        interactive : ${{ github.event.inputs.interactive }}
        product-id: 9NP0T3QQXL70
        package-path: "${{ github.workspace }}/dir/apps"
        photos-path: "${{ github.workspace }}/dir/photos"
        json-file-path: "${{ github.workspace }}/dir/metadata.json"
        
