name: msstore-setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-msstore-cli:
    runs-on: ubuntu-latest  # Adjust for your target OS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET Runtime
        run: |
          wget https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-7.0.10-linux-x64-binaries
          tar -xvf runtime-7.0.10-linux-x64-binaries
          sudo mv dotnet /usr/local/share/dotnet
          sudo ln -s /usr/local/share/dotnet/dotnet /usr/local/bin/dotnet

      - name: Install msstore-cli
        run: |
          wget https://github.com/microsoft/msstore-cli/releases/latest/download/MSStoreCLI-linux-x64.tar.gz
          tar -xvf MSStoreCLI-linux-x64.tar.gz
          sudo mv MSStoreCLI /usr/local/bin/msstore-cli

      - name: Reconfigure msstore-cli
        run: |
          msstore reconfigure \
            -c "${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}" \
            -cs "${{ secrets.AZURE_AD_APPLICATION_SECRET }}" \
            -t "${{ secrets.AZURE_AD_TENANT_ID }}" \
            -s "${{ secrets.SELLER_ID }}" \
            --appId "${{ secrets.STORE_APP_ID }}" 

      - name: List available apps
        run: msstore apps list
