name: myUpdate
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run AutoPublisher
      uses: adityak1429/autopublisher_cli@main
      with:
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
        seller-id: ${{ secrets.SELLER_ID }}
        command: publish
        product-id: 9NP0T3QQXL70
        type: msix
        package: "${{ github.workspace }}/FF/app"
        photos-path: "${{ github.workspace }}/FF/pics"
        json-file-path: "${{ github.workspace }}/FF/metadata.json"
        append: false
        
