name: Setup StoreBroker

on:
  push:
    branches:
      - main

jobs:
  setup-storebroker:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Optional: Install specific version of PowerShell Core (only if needed)
    - name: Install PowerShell 7.2.0
      shell: powershell
      run: |
        $msi = "$env:TEMP\PowerShell-7.2.0-win-x64.msi"
        Invoke-WebRequest -Uri "https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/PowerShell-7.2.0-win-x64.msi" -OutFile $msi
        Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /quiet /norestart" -Wait

    # Use pwsh (PowerShell Core) for the following steps
    - name: Install StoreBroker module
      shell: pwsh
      run: |
        Install-Module -Name StoreBroker -Force -Scope CurrentUser

    - name: Verify StoreBroker installation
      shell: pwsh
      run: |
        Get-Command -Module StoreBroker
