name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: List contents of github.workspace
        run: ls -R ${{ github.workspace }}
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List contents of github.workspace
        run: ls -R ${{ github.workspace }}

      - name: Publish to Microsoft Store
        uses: isaacrlevin/windows-store-action@1.0
        with:
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
          app-id: ${{ secrets.STORE_APP_ID }}
          package-path: ${{ github.workspace }}
