name: Check Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret is empty
        run: |
          if [ -z "${{ secrets.AZURE_AD_APPLICATION_SECRET }}" ]; then
            echo "TEST_SECRET is empty!"
            exit 1
          else
            echo "TEST_SECRET is set."
          fi
